syntax = "proto3";

option go_package = "go_grpc/proto";

package kvservice;

service KVService {
  rpc Put(PutRequest) returns (PutResponse);
  rpc Swap(SwapRequest) returns (SwapResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc Scan(ScanRequest) returns (ScanResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
}

message PutRequest {
  string key = 1;
  string value = 2;
}

message SwapRequest {
  string key = 1;
  string value = 2;
}

message GetRequest {
  string key = 1;
}

message ScanRequest {
  string start_key = 1;
  string end_key = 2;
}

message DeleteRequest {
  string key = 1;
}


message PutResponse{
  bool already_exists = 1;
}

message SwapResponse{
  string old_value = 1;
  bool exists = 2;
}

message GetResponse{
  string value = 1;
  bool exists = 2;
}

message KeyValue {
  string key = 1;
  string value = 2;
}

message ScanResponse {
  repeated KeyValue entries = 1;
}

message DeleteResponse{
  bool exists = 1;
}